# This workflow will generate any code then check for any git diff

name: Modular Docs Publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up JDK 9.0.4 for x64
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - run: npm --prefix .build install
    - run: npm --prefix .build run generate:modular-docs
      name: generate modular-docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.build/tmp/post-splitter
        publish_branch: modular-docs

