# This workflow will generate any code then check for any git diff

name: Modular docs generation

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      name: Checkout Source
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up JDK 9.0.4 for x64
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - run: npm --prefix .build install
      name: Install Dependencies
    - run: npm --prefix .build run generate:modular-docs
      name: Generate modular-docs
